# Drill-down data endpoint (logging_db)
@app.route('/api/drilldown/deliverables')
def drilldown_deliverables():
    # TODO: Query logging_db for deliverables records
    from email_engine.logging_db import get_deliverables_records
    records = get_deliverables_records()
    return jsonify({'records': records})

# Drill-down data endpoint (analytics API)
@app.route('/api/drilldown/escalations')
def drilldown_escalations():
    # TODO: Query analytics API for escalation records
    # Simulate with static data for now
    records = [{'id':1,'status':'active','detail':'PPT pending','timestamp':'2026-03-08'}]
    return jsonify({'records': records})

# CSV/Excel export endpoint for filtered views
@app.route('/api/export/csv', methods=['POST'])
def export_csv():
    data = request.get_json()
    records = data.get('records',[])
    role = data.get('role','user')
    # TODO: Role-based access control
    if role not in ['admin','leadership','user']:
        return jsonify({'error':'Access denied'}),403
    import csv, io
    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=records[0].keys() if records else [])
    writer.writeheader()
    writer.writerows(records)
    csv_data = output.getvalue()
    # Notify leadership via Slack
    import requests as pyrequests
    SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/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"
    pyrequests.post(SLACK_WEBHOOK_URL, json={"text":f"CSV export generated by {role}."})
    return csv_data, 200, {'Content-Type':'text/csv','Content-Disposition':'attachment; filename="dashboard_export.csv"'}

# Excel export endpoint
@app.route('/api/export/excel', methods=['POST'])
def export_excel():
    data = request.get_json()
    records = data.get('records',[])
    role = data.get('role','user')
    if role not in ['admin','leadership','user']:
        return jsonify({'error':'Access denied'}),403
    import pandas as pd
    df = pd.DataFrame(records)
    excel_bytes = df.to_excel(index=False, engine='xlsxwriter')
    # Notify leadership via Slack
    import requests as pyrequests
    SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/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"
    pyrequests.post(SLACK_WEBHOOK_URL, json={"text":f"Excel export generated by {role}."})
    return excel_bytes, 200, {'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':'attachment; filename="dashboard_export.xlsx"'}

# Slack notification endpoint for leadership updates (integrated with Slack webhook)
import requests as pyrequests
SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/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"
@app.route('/api/notify-leadership', methods=['POST'])
def notify_leadership():
    data = request.get_json()
    message = data.get('message', '')
    payload = {"text": message}
    resp = pyrequests.post(SLACK_WEBHOOK_URL, json=payload)
    return jsonify({'status': 'sent', 'message': message, 'slack_response': resp.text}), 200

# Scheduled export automation (weekly/monthly)
import threading, time
def scheduled_export_job():
    while True:
        now = time.localtime()
        # Weekly export: Friday 17:00
        if now.tm_wday == 4 and now.tm_hour == 17 and now.tm_min == 0:
            # TODO: Export executive summary as PDF and email to leadership
            print("Weekly executive summary export triggered.")
        # Monthly export: Last day of month 17:00
        last_day = time.localtime(time.mktime((now.tm_year, now.tm_mon+1, 1, 0, 0, 0, 0, 0, 0)) - 86400).tm_mday
        if now.tm_mday == last_day and now.tm_hour == 17 and now.tm_min == 0:
            # TODO: Export monthly summary as PDF and email to leadership
            print("Monthly executive summary export triggered.")
        time.sleep(60)

# Start scheduled export job in background thread
threading.Thread(target=scheduled_export_job, daemon=True).start()

# Export endpoint for Sprint 28 Executive Summary (Quick Recap) with branding, layout, and metrics
@app.route('/api/export-sprint28-recap/<fmt>')
def export_sprint28_recap(fmt):
    recap_html = '''<div style="background:#fffbe6;border:2px solid #b7950b;margin-bottom:30px;border-radius:8px;padding:24px;font-family:'Segoe UI',Arial,sans-serif;">
        <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:16px;">
            <img src="/static/company_logo.png" alt="Company Logo" style="height:48px;">
            <h2 style="color:#2980b9;margin:0;">Sprint 28 Executive Summary</h2>
            <span style="color:#b7950b;font-size:1.1em;font-weight:bold;">Prepared by Richard Norman— Sprint 28</span>
        </div>
        <div style="background:#eaf6ff;border-radius:8px;padding:16px;margin-bottom:16px;display:flex;gap:24px;">
            <div style="flex:1;">
                <h3 style="color:#27ae60;margin-bottom:8px;">Green (Completed)</h3>
                <ul>
                    <li>Facilitator Toolkit finalized</li>
                    <li>Exercise Outline ready</li>
                    <li>Kanban Templates bundled</li>
                    <li>Icon Files prepared</li>
                </ul>
            </div>
            <div style="flex:1;">
                <h3 style="color:#f39c12;margin-bottom:8px;">Amber (Pending)</h3>
                <ul>
                    <li>Polished PPT design pending</li>
                    <li>Escalation issued for delivery today</li>
                </ul>
            </div>
            <div style="flex:1;">
                <h3 style="color:#e74c3c;margin-bottom:8px;">Red (Blocked)</h3>
                <ul>
                    <li>Dashboard launch dependent on PPT delivery</li>
                    <li>Wireframe contingency ready</li>
                </ul>
            </div>
        </div>
        <div style="display:flex;gap:24px;margin-bottom:16px;">
            <div style="flex:1;background:#fff;border-radius:8px;padding:16px;">
                <h4 style="color:#2980b9;margin-bottom:8px;">Key Metrics</h4>
                <ul style="font-size:1.05em;">
                    <li>Deliverables completed: <span style="color:#27ae60;font-weight:bold;">4</span></li>
                    <li>Deliverables pending: <span style="color:#f39c12;font-weight:bold;">1</span></li>
                    <li>Escalations raised: <span style="color:#f39c12;font-weight:bold;">1</span></li>
                    <li>Escalations resolved: <span style="color:#27ae60;font-weight:bold;">0</span></li>
                    <li>Dashboard launch readiness: <span style="color:#2980b9;font-weight:bold;">Ready</span></li>
                    <li>Contingency plan: <span style="color:#27ae60;font-weight:bold;">Available</span></li>
                </ul>
            </div>
            <div style="flex:1;background:#fff;border-radius:8px;padding:16px;">
                <h4 style="color:#2980b9;margin-bottom:8px;">Additional Executive Metrics</h4>
                <ul style="font-size:1.05em;">
                    <li>Delivery stats: <span style="color:#27ae60;">80% completed, 20% pending</span></li>
                    <li>Compliance: <span style="color:#27ae60;">All deadlines met except PPT</span></li>
                    <li>Engagement: <span style="color:#2980b9;">Leadership visibility, stakeholder updates sent</span></li>
                    <li>Risk: <span style="color:#f39c12;">Escalation active, contingency plan ready</span></li>
                    <li>Readiness: <span style="color:#27ae60;">Dashboard launch cleared</span></li>
                </ul>
            </div>
        </div>
        <div style="margin-top:16px;font-size:1.05em;color:#888;">
            <strong>Sprint 28 update:</strong> All core deliverables (toolkit, outline, templates, icons) are finalized and bundled <span style="color:#27ae60;">✅</span>. The polished PPT is still pending but escalation is in progress <span style="color:#f39c12;">⚠️</span>. Dashboard launch remains on track <span style="color:#2980b9;">🚀</span> — wireframe contingency is ready if needed. The final package will be shared as soon as the PPT is delivered.
        </div>
        <div style="margin-top:16px;text-align:center;color:#b7950b;font-size:0.95em;">© 2026 Company Name. All rights reserved.</div>
    </div>'''
    if fmt == 'html':
        return recap_html, 200, {'Content-Type': 'text/html'}
    elif fmt == 'pdf':
        import pdfkit
        pdf = pdfkit.from_string(recap_html, False)
        return pdf, 200, {'Content-Type': 'application/pdf', 'Content-Disposition': 'attachment; filename="Sprint28_Executive_Recap.pdf"'}
    else:
        return jsonify({'error': 'Invalid format'}), 400

# Export endpoint for Sprint 28 Dashboard Status Snapshot & Q&A Cheat Sheet
@app.route('/api/export-sprint28-status/<fmt>')
def export_sprint28_status(fmt):
    panel_html = '''<div style="background:#eaf6ff;border:2px solid #2980b9;margin-bottom:30px;border-radius:8px;padding:24px;">
        <h2 style="color:#2980b9;">Sprint 28 Dashboard Status Snapshot</h2>
        <ul style="font-size:1.05em;">
            <li><strong style="color:#27ae60;">Green (Completed):</strong>
                <ul>
                    <li>Facilitator Toolkit finalized</li>
                    <li>Exercise Outline ready</li>
                    <li>Kanban Templates bundled</li>
                    <li>Icon Files prepared</li>
                </ul>
            </li>
            <li><strong style="color:#f39c12;">Amber (Pending):</strong>
                <ul>
                    <li>Polished PPT design still in progress</li>
                    <li>Delivery reminder/escalation sent</li>
                </ul>
            </li>
            <li><strong style="color:#e74c3c;">Red (Blocked):</strong>
                <ul>
                    <li>Dashboard launch dependent on PPT delivery</li>
                </ul>
            </li>
        </ul>
        <div style="margin-top:16px;font-size:1.1em;color:#2980b9;font-weight:bold;">Backup Talking Points (assertive):</div>
        <ul style="font-size:1.05em;">
            <li>“The delay was due to design polish only — all core materials were completed and bundled on time. I’ve already escalated directly to the owner to secure delivery today.”</li>
            <li>“We have a contingency wireframe version ready, so the dashboard launch is not at risk. Leadership visibility is in place, and I’m driving closure to keep us on schedule.”</li>
        </ul>
        <hr style="margin:24px 0;">
        <h2 style="color:#2980b9;">Sprint 28 Q&A Cheat Sheet</h2>
        <ul style="font-size:1.05em;">
            <li><strong>Q: Why was the polished PPT delayed?</strong><br>
                <span style="color:#888;">A: The delay was limited to design polish only. All core materials were completed and bundled on time. I escalated directly to the owner and secured delivery today.</span>
            </li>
            <li><strong>Q: Is the dashboard launch at risk?</strong><br>
                <span style="color:#888;">A: No — we have a contingency wireframe version ready. The dashboard can go live as scheduled once the polished PPT is handed off.</span>
            </li>
            <li><strong>Q: How are you ensuring accountability?</strong><br>
                <span style="color:#888;">A: Leadership visibility is already in place. I’ve issued a final escalation and set a hard deadline. I’ll close the loop with a success acknowledgment once delivery is confirmed.</span>
            </li>
            <li><strong>Q: What’s the impact if the PPT isn’t delivered today?</strong><br>
                <span style="color:#888;">A: Minimal — the dashboard can launch with the wireframe version. The polished PPT will follow immediately after, so there’s no disruption to readiness activities.</span>
            </li>
        </ul>
        <hr style="margin:24px 0;">
        <div style="font-size:1.1em;color:#2980b9;font-weight:bold;">Closing Statement:</div>
        <div style="margin-top:8px;font-size:1.05em;color:#2980b9;">
            In summary, Sprint 28 deliverables are complete, with only the polished PPT pending final handoff today. We have contingencies in place, so the dashboard launch remains on track and fully supported.<br>
            I’ll ensure leadership receives the final package immediately upon delivery, and we’re positioned to move forward without disruption.
        </div>
    </div>'''
    if fmt == 'html':
        return panel_html, 200, {'Content-Type': 'text/html'}
    elif fmt == 'pdf':
        import pdfkit
        pdf = pdfkit.from_string(panel_html, False)
        return pdf, 200, {'Content-Type': 'application/pdf', 'Content-Disposition': 'attachment; filename="Sprint28_Status_Snapshot.pdf"'}
    else:
        return jsonify({'error': 'Invalid format'}), 400

# Dashboard UI (real-time analytics, bounce stats, engagement metrics)
from flask import Flask, render_template, jsonify, request, abort
import json
import os
import pathlib
import requests

# Set template folder to dashboard directory
BASE_DIR = pathlib.Path(__file__).parent
app = Flask(__name__, template_folder=str(BASE_DIR))

@app.route('/')
def index():
    return render_template('dashboard.html')

# Panel Endpoints
@app.route('/api/export/feedback')
def export_feedback():
    # TODO: Connect to feedback DB
    return jsonify({
        'recent_comments': ['Great dashboard!', 'Needs more export options.'],
        'sentiment_score': 0.87,
        'feedback_trend': 0.05
    })

@app.route('/api/export/performance')
def export_performance():
    # TODO: Connect to logging_db.py
    return jsonify({
        'server_load': 0.42,
        'response_time': 0.21,
        'error_rate': 0.008,
        'uptime': 0.999
    })

@app.route('/api/export/engagement')
def export_engagement():
    # TODO: Connect to analytics platform
    return jsonify({
        'avg_session_duration': '7m 12s',
        'click_through_rate': 0.42,
        'feature_usage': 'Heatmap available',
        'drop_off_points': ['Settings', 'Export']
    })

@app.route('/api/export/data-export')
def export_data_export():
    # TODO: Connect to audit logs/export tracking DB
    return jsonify({
        'export_volume': 320,
        'top_file_type': 'CSV',
        'peak_export_hour': '11:00 AM',
        'user_roles': ['Admin', 'Analyst', 'Manager']
    })

@app.route('/api/export/world-data')
def export_world_data():
    # TODO: Connect to global user activity DB
    return jsonify({
        'active_sessions': 1240,
        'top_regions': ['US', 'UK', 'India', 'Germany'],
        'growth_trend': 0.12
    })

@app.route('/api/export/tes')
def export_tes():
    # TODO: Connect to TES delivery logs/compliance checks
    return jsonify({
        'delivery_stats': {'latency': 0.32, 'provider_routing': {'SES': 0.6, 'SendGrid': 0.25, 'Mailgun': 0.15}, 'failover_events': 2},
        'compliance_status': {'SPF': True, 'DKIM': True, 'DMARC': True, 'TLS_coverage': 0.99},
        'bounce_suppression': {'hard_bounces': 12, 'soft_bounces': 34, 'complaints': 3, 'suppression_list_entries': 18},
        'template_insights': {'password_resets': {'sent': 420, 'open_rate': 0.68}, 'alerts': {'sent': 310, 'open_rate': 0.54}, 'receipts': {'sent': 180, 'open_rate': 0.72}, 'quiet_hours_impact': -0.08},
        'system_health': {'retry_queue_depth': 6, 'circuit_breaker_triggers': 1, 'sla_monitoring': 0.998}
    })

@app.route('/api/export/gamification')
def export_gamification():
    # TODO: Connect to engagement DB
    return jsonify({
        'badges_earned': 42,
        'participation_rate': 0.78,
        'quarterly_titans': 3
    })

@app.route('/api/export/threat-trends')
def export_threat_trends():
    # TODO: Connect to SOC feeds
    return jsonify({
        'threat_types': ['Phishing', 'Malware', 'Quishing'],
        'frequency': [12, 8, 5],
        'trend_lines': [10, 9, 7]
    })

@app.route('/api/export/compliance')
def export_compliance():
    # TODO: Connect to compliance audit DB
    return jsonify({
        'departments': [
            {'name': 'IT', 'spf': True, 'dkim': True, 'dmarc': True, 'score': 98, 'badge': 'Compliance Guardian'},
            {'name': 'Finance', 'spf': True, 'dkim': True, 'dmarc': False, 'score': 85, 'badge': 'Engagement Star'},
            {'name': 'HR', 'spf': True, 'dkim': False, 'dmarc': True, 'score': 90, 'badge': 'Detection Hero'}
        ]
    })

@app.route('/api/live-alerts')
def live_alerts():
    # TODO: Connect to alerts/admin notifications service
    return jsonify({
        'real_time_alerts': 2,
        'scheduled_maintenance': '2026-03-10 02:00',
        'user_reminders': 5
    })

# Incident Logging & Escalation
@app.route('/api/log-incident', methods=['POST'])
def log_incident():
    data = request.get_json()
    # TODO: Store incident in compliance audit DB
    incident = {
        'type': data.get('type'),
        'severity': data.get('severity'),
        'timestamp': data.get('timestamp'),
        'details': data.get('details')
    }
    # Simulate storing
    return jsonify({'status': 'logged', 'incident': incident}), 201

@app.route('/api/escalate-incident', methods=['POST'])
def escalate_incident():
    data = request.get_json()
    # TODO: Escalate incident to senior admin/leadership
    escalation = {
        'incident_id': data.get('incident_id'),
        'escalation_level': data.get('level'),
        'timestamp': data.get('timestamp')
    }
    # Simulate escalation
    return jsonify({'status': 'escalated', 'escalation': escalation}), 200

@app.route('/api/archive-alert', methods=['POST'])
def archive_alert():
    data = request.get_json()
    # TODO: Archive resolved alert after 7 days
    alert_id = data.get('alert_id')
    severity = data.get('severity')
    # Simulate archiving
    return jsonify({'status': 'archived', 'alert_id': alert_id, 'severity': severity}), 200


# Role-based access control (scaffold)
def check_role(required_role):
    # Example: check user role from session or request
    role = request.args.get('role', 'user')
    if role != required_role:
        abort(403)

# External service integration (Slack, ServiceNow)
def send_slack_notification(message):
    slack_webhook = 'https://hooks.slack.com/services/YOUR/WEBHOOK/URL'
    payload = {'text': message}
    requests.post(slack_webhook, json=payload)

def create_servicenow_incident(description):
    servicenow_url = 'https://instance.service-now.com/api/now/table/incident'
    headers = {'Authorization': 'Bearer YOUR_TOKEN', 'Content-Type': 'application/json'}
    payload = {'short_description': description}
    requests.post(servicenow_url, headers=headers, json=payload)

# JWT, OAuth, session, role hierarchy access control
from flask_jwt_extended import JWTManager, jwt_required, get_jwt_identity
from flask import session

app.config['JWT_SECRET_KEY'] = 'your_jwt_secret_key'
jwt = JWTManager(app)

# Example: role hierarchy
ROLE_HIERARCHY = {'admin': 3, 'manager': 2, 'user': 1}

def check_access(required_role):
    user_role = session.get('role', 'user')
    if ROLE_HIERARCHY.get(user_role, 0) < ROLE_HIERARCHY.get(required_role, 0):
        abort(403)

from email_engine.dashboard.device_analytics_panel import device_analytics_panel
from email_engine.dashboard.geo_heatmap_panel import geo_heatmap_panel
from email_engine.dashboard.escalation_workflow_panel import escalation_workflow_panel
from email_engine.dashboard.compliance_audit_panel import compliance_audit_panel
from email_engine.dashboard.external_api_panel import external_api_panel

app.register_blueprint(device_analytics_panel)
app.register_blueprint(geo_heatmap_panel)
app.register_blueprint(escalation_workflow_panel)
app.register_blueprint(compliance_audit_panel)
app.register_blueprint(external_api_panel)
from email_engine.dashboard.threat_intel_panel import threat_intel_panel
from email_engine.dashboard.audit_logs_panel import audit_logs_panel
from email_engine.dashboard.predictive_analytics_panel import predictive_analytics_panel
from email_engine.dashboard.custom_alerts_panel import custom_alerts_panel

app.register_blueprint(audit_logs_panel)
app.register_blueprint(predictive_analytics_panel)
from email_engine.dashboard.risk_panel import risk_panel
from email_engine.dashboard.compliance_trends_panel import compliance_trends_panel
from email_engine.dashboard.user_activity_panel import user_activity_panel
from email_engine.dashboard.external_integration_panel import external_integration_panel

app.register_blueprint(risk_panel)
app.register_blueprint(compliance_trends_panel)
app.register_blueprint(user_activity_panel)
app.register_blueprint(external_integration_panel)
from email_engine.dashboard.anomaly_panel import anomaly_panel
from email_engine.dashboard.workflow_panel import workflow_panel
from email_engine.dashboard.analytics_panel import analytics_panel

app.register_blueprint(anomaly_panel)
app.register_blueprint(workflow_panel)
app.register_blueprint(analytics_panel)
@app.route('/api/secure-data')
@jwt_required()
def secure_data():
    user = get_jwt_identity()
    check_access('manager')
    return jsonify({'data': 'secure for managers and above', 'user': user})

# OAuth scaffold (e.g., Google, Microsoft)
from email_engine.dashboard.suppression_panel import suppression_panel
from email_engine.dashboard.queue_panel import queue_panel
from email_engine.dashboard.deliverability_panel import deliverability_panel
from email_engine.dashboard.tracking_panel import tracking_panel
from email_engine.dashboard.advanced_metrics_panel import advanced_metrics_panel
from email_engine.dashboard.user_management_panel import user_management_panel
from email_engine.dashboard.reputation_panel import reputation_panel
from email_engine.dashboard.compliance_panel import compliance_panel
from email_engine.dashboard.observability_panel import observability_panel
from email_engine.dashboard.threat_intel_panel import threat_intel_panel
from email_engine.dashboard.sla_panel import sla_panel
from email_engine.dashboard.volume_trends_panel import volume_trends_panel
from email_engine.dashboard.custom_alerts_panel import custom_alerts_panel

app.register_blueprint(suppression_panel)
app.register_blueprint(queue_panel)
app.register_blueprint(deliverability_panel)
app.register_blueprint(tracking_panel)
app.register_blueprint(advanced_metrics_panel)
app.register_blueprint(user_management_panel)
app.register_blueprint(reputation_panel)
app.register_blueprint(compliance_panel)
app.register_blueprint(observability_panel)
app.register_blueprint(sla_panel)
app.register_blueprint(volume_trends_panel)
app.register_blueprint(custom_alerts_panel)

# OAuth provider support
@app.route('/oauth/login/google')
def oauth_login_google():
    return redirect('https://accounts.google.com/o/oauth2/auth?client_id=YOUR_CLIENT_ID&redirect_uri=YOUR_REDIRECT_URI&response_type=code&scope=email profile')

@app.route('/oauth/login/microsoft')
def oauth_login_microsoft():
    return redirect('https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=YOUR_CLIENT_ID&redirect_uri=YOUR_REDIRECT_URI&response_type=code&scope=openid email profile')

@app.route('/oauth/login/custom')
def oauth_login_custom():
    return redirect('https://custom-oauth-provider.com/auth?client_id=YOUR_CLIENT_ID&redirect_uri=YOUR_REDIRECT_URI&response_type=code&scope=email profile')

# Advanced Slack/ServiceNow templates

def send_slack_notification(message, severity='info'):
    slack_webhook = 'https://hooks.slack.com/services/YOUR/WEBHOOK/URL'
    payload = {'text': f'[{severity.upper()}] {message}'}
    requests.post(slack_webhook, json=payload)

def create_servicenow_incident(description, urgency='medium'):
    servicenow_url = 'https://instance.service-now.com/api/now/table/incident'
    headers = {'Authorization': 'Bearer YOUR_TOKEN', 'Content-Type': 'application/json'}
    payload = {'short_description': description, 'urgency': urgency}
    requests.post(servicenow_url, headers=headers, json=payload)

# Fine-grained access control
@app.route('/api/admin-data')
@jwt_required()
def admin_data():
    user = get_jwt_identity()
    check_access('admin')
    return jsonify({'data': 'admin only', 'user': user})

# Real-time endpoint optimization
@app.route('/api/live-alerts')
def live_alerts():
    # Return latest alerts for dashboard
    from email_engine.dashboard.custom_alerts_panel import get_custom_alerts
    return get_custom_alerts()

if __name__ == '__main__':
    app.run(debug=True, port=5000)
